TiendaVirtualWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TiendaVirtualWeb.Models;

namespace TiendaVirtualWeb.Controllers
{
    public class HomeController : Controller
    {
        private TiendaVirtualEntities db = new TiendaVirtualEntities();
        dynamic carroCompraModel = new ExpandoObject();
        public ActionResult Index(string busqueda, CarroCompra carroCompra)
        {
            if (busqueda == null || busqueda == "")
            {
                carroCompraModel.Productos = db.Productoes.ToList().FindAll(p => p.pro_cantidad > Constantes.productoEliminado);
            }
            else
            {

                carroCompraModel.Productos = db.Productoes.ToList().FindAll(
                        p => p.pro_cantidad > Constantes.productoEliminado &&
                         (p.pro_nombre.ToLower().Contains(busqueda)
                        || p.pro_descripcion.ToLower().Contains(busqueda)
                        || p.pro_categoria.ToLower().Contains(busqueda)
                        || p.pro_autor.ToLower().Contains(busqueda)
                        || p.pro_isbn.ToLower().Contains(busqueda)));
            }

            carroCompraModel.ProductosCarro = carroCompra;
            return View(carroCompraModel);


        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TiendaVirtualWeb/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaVirtualWeb;
using TiendaVirtualWeb.Models;

namespace TiendaVirtualWeb.Controllers
{

    public class ProductosController : Controller
    {
        private TiendaVirtualEntities db = new TiendaVirtualEntities();
        dynamic carroCompraModel = new ExpandoObject();


        // GET: Productos
        [Authorize(Roles = "admin")]
        public ActionResult Index(CarroCompra carroCompra)
        {
            carroCompraModel.Productos = db.Productoes.ToList();
            carroCompraModel.ProductosCarro = carroCompra;
            return View(carroCompraModel);

        }

        // GET: Productos/Details/5
        [Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // GET: Productos/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Productos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,pro_nombre,pro_cantidad,pro_precio,pro_descripcion,por_imagen,pro_categoria,pro_autor,pro_isbn")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                producto.pro_fecha_registro = DateTime.Now;
                db.Productoes.Add(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(producto);
        }

        // GET: Productos/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,pro_nombre,pro_cantidad,pro_precio,pro_descripcion,por_imagen,pro_categoria,pro_autor,pro_isbn")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                producto.pro_fecha_registro = DateTime.Now;
                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(producto);
        }

        // GET: Productos/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producto producto = db.Productoes.Find(id);
            producto.pro_cantidad = Constantes.productoEliminado;
            db.Entry(producto).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddProdutoCarro(int id, CarroCompra carroCompra)
        {
            int contadorProductos = 1;
            Producto producto = db.Productoes.Find(id);
            if ((carroCompra.Count != 0) && (carroCompra.Exists(p => p.Id == id)))
            {
                if (producto.pro_cantidad > carroCompra.Find(p => p.Id == id).pro_cantidad)
                {
                    carroCompra.Find(p => p.Id == id).pro_cantidad += contadorProductos;
                }

            }
            else
            {
                if (producto.pro_cantidad > 0)
                {
                    carroCompra.Add(producto);
                    carroCompra.Find(p => p.Id == id).pro_cantidad = contadorProductos;
                }

            }

            return RedirectToAction("Index", "Home");

        }
        public ActionResult RemoverProdutoCarro(int id, CarroCompra carroCompra)
        {
            carroCompra.RemoveAll(p => p.Id == id);
            return RedirectToAction("ListarProdutoCarro");

        }
        public ActionResult ListarProdutoCarro(CarroCompra carroCompra)
        {

            carroCompraModel.ProductosCarro = carroCompra;
            carroCompraModel.Productos = db.Productoes.ToList();
            return View(carroCompraModel);

        }
        public ActionResult GenerarPedido(CarroCompra carroCompra)
        {
            /*TODO: De momento datos quemados para cliente
             */
            if (User.Identity.IsAuthenticated)
            {
                Random rnd = new Random();
                String valor = Convert.ToString(rnd.Next(0, 20));
                Pedido pedido = new Pedido();
                List<ProductoPedido> productosPedidos = new List<ProductoPedido>();
                List<Producto> productos = new List<Producto>();
                Cliente cliente = new Cliente();
                Producto producto = new Producto();
                decimal precioTotalCompra = 0;
                if ((db.Clientes.ToList().Exists(c => c.usu_id == User.Identity.Name)))
                {
                    cliente =
                            (from c in db.Clientes.ToList()
                            where c.usu_id == User.Identity.Name
                            select c).First();

                }
                else
                {
                    return RedirectToAction("Create", "Clientes");

                }

                pedido.ped_estado = 1;
                pedido.ped_fecha_registro = DateTime.Now;
                pedido.Cliente = cliente;
                pedido.ped_total_productos = carroCompra.Sum(p => p.pro_cantidad);
                foreach (var item in carroCompra)
                {
                    ProductoPedido productoPedido = new ProductoPedido();
                    Producto productoTemp = db.Productoes.Find(item.Id);
                    productoTemp.pro_cantidad -= item.pro_cantidad;
                    precioTotalCompra += item.pro_cantidad * item.pro_precio;
                    productoPedido.Pedido = pedido;
                    productoPedido.pro_id = item.Id;
                    productoPedido.prp_catidad_producto = item.pro_cantidad;
                    productoPedido.prp_fecha_registro = DateTime.Now;
                    db.ProductoPedidoes.Add(productoPedido);
                    db.Entry(productoTemp).State = EntityState.Modified;
                }

                pedido.ped_monto = precioTotalCompra;
                db.Pedidoes.Add(pedido);
                db.SaveChanges();
                carroCompra.Clear();
                carroCompraModel.ProductosCarro = carroCompra;
                return RedirectToAction("Index", "Pedidos");
            }
           
            return RedirectToAction("Login", "Account");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TiendaVirtualWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TiendaVirtualWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TiendaVirtualWeb/Views/Home/Index.cshtml
@model dynamic
@{
    ViewBag.Title = "Tienda";
}

@{
    var totalProductos = 0;
    foreach (Producto item in Model.ProductosCarro)
    {
        totalProductos += item.pro_cantidad;
    }

}
<br />
<a href="@Url.Action("ListarProdutoCarro", "Productos", null, null)" class="btn btn-danger">
    <span class="glyphicon glyphicon-shopping-cart"> </span>
    (@totalProductos)
</a>

<div class="container">
    <br />
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="navbar-form navbar-right">
                @using (Html.BeginForm("Index", "Home", FormMethod.Get))
                {
                    <div class="form-group">
                        <input id="busqueda" name="busqueda" type="text" class="form-control" placeholder="Buscar">
                    </div>
                    <input type="submit" value="Buscar" class="btn btn-default" />
                }
            </div>
        </div>
    </div>
</div>

@foreach (Producto item in Model.Productos)
{

    <div class="row">
        <div class="col-md-2">
            <img class="img-responsive" style="width:100%;"
                 src="~/Content/imagenes/@Html.DisplayFor(modelItem => item.por_imagen)"
                 alt="imagen" />
        </div>
        <div class="col-md-8">
            <h2 class="text-primary">@Html.DisplayFor(modelItem => item.pro_nombre)</h2>
            <p class="text-info">
                @Html.DisplayFor(modelItem => item.pro_descripcion)
            </p>
            <p class="text-muted">
                <strong>Autor:</strong> @Html.DisplayFor(modelItem => item.pro_autor) <strong>|</strong>
                <strong>ISBN:</strong> @Html.DisplayFor(modelItem => item.pro_isbn)
            </p>

            <p class="text-danger">
                <strong>€ @Html.DisplayFor(modelItem => item.pro_precio)</strong>
            </p>
            <a id="stock" href="@Url.Action("AddProdutoCarro", "Productos", new { id = item.Id },null)"
               class="btn btn-success">
                <span class="glyphicon glyphicon-shopping-cart"> </span>
                Agregar al Carro
            </a>
        </div>
        <div class="col-md-2">
            @if (item.pro_cantidad > 0)
                {

                    if (item.pro_cantidad > 6)
                    {
                    <h2 class="text-center text-success">Disponibles</h2>
                    <h1 class="text-center text-success">
                        <strong>@Html.DisplayFor(modelItem => item.pro_cantidad)</strong>
                    </h1>
                }
                else
                {
                    <h2 class="text-center text-danger">Disponibles</h2>
                    <h1 class="text-center text-danger">
                        <strong>@Html.DisplayFor(modelItem => item.pro_cantidad)</strong>
                    </h1>
                    <p class="text-center text-danger">Adquierelo pronto, estan por agotarce!!!</p>
                }
            }
            else
            {
                <img class="img-responsive" style="width:100%;"
                     src="~/Content/imagenes/agotado2.jpg"
                     alt="agotado" />
            }

        </div>
    </div>
    <hr class="alert-success" />
}